backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from core import views
from core.routers import todo_router

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include(todo_router.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path("todos/", include("core.urls")),
    path("", views.HomeTemplateView.as_view(), name='home'),
]

backend/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('', views.TodoListView.as_view(), name='todo_list'),
    path('create/', views.TodoCreateView.as_view(), name='todo_create'),
    path('<int:pk>/', views.TodoDetailView.as_view(), name='todo_detail'),
    path('<int:pk>/update/', views.TodoUpdateView.as_view(), name='todo_update'),
    path('<int:pk>/delete/', views.TodoDeleteView.as_view(), name='todo_delete'),
    path('<int:pk>/completed/', views.TodoUpdateCompletedView.as_view(), name='todo_update_completed'),
]

todo_backend/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

backend/core/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    """Todo Model"""

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    due_date = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

backend/core/forms.py
from django import forms

from core.models import Todo


class TodoForm(forms.ModelForm):
    """Base Todo Form with common functionality"""

    class Meta:
        model = Todo
        fields = ('title', 'description', 'due_date')
        widgets = {
            # TODO: Ensure the due date is not in the past
            'due_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
            }),
        }


class TodoCreateForm(TodoForm):
    """Todo Create Form"""
    
    class Meta(TodoForm.Meta):
        fields = ('title', 'description', 'due_date')


class TodoUpdateForm(TodoForm):
    """Todo Update Form"""
    
    class Meta(TodoForm.Meta):
        fields = ('title', 'description', 'is_completed', 'due_date')


class TodoUpdateCompletedForm(forms.Form):
    """Todo Update Completed From"""

    completed = forms.BooleanField(required=False)

backend/core/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, DeleteView, TemplateView, CreateView, UpdateView, View

from core.models import Todo
from core.forms import TodoCreateForm, TodoUpdateCompletedForm, TodoUpdateForm

# Create your views here.

class HomeTemplateView(TemplateView):
    """Home Template View"""

    template_name='core/home.html'


class TodoListView(ListView):
    """Todo List View"""

    model = Todo


class TodoDetailView(DetailView):
    """Todo Detail View"""
    
    model = Todo


class TodoDeleteView(DeleteView):
    """Todo Delete View"""
    
    model = Todo
    success_url = reverse_lazy("core:todo_list")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Todo successfully deleted.')
        return response

class TodoCreateView(CreateView):
    """Todo Create View"""

    model = Todo
    form_class = TodoCreateForm
    template_name_suffix= '_create'
    success_url = reverse_lazy("core:todo_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Todo successfully created.')
        return response

class TodoUpdateView(UpdateView):
    """Todo Update View"""

    model = Todo
    form_class = TodoUpdateForm
    template_name_suffix= '_update'
    success_url = reverse_lazy("core:todo_list")
        
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Todo successfully updated.')
        return response


class TodoUpdateCompletedView(View):
    """Todo Update Completed"""

    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        """Method to handle todo completed post request"""

        todo = get_object_or_404(Todo, pk=pk)
        form = TodoUpdateCompletedForm(request.POST)

        if form.is_valid():
            is_completed = form.cleaned_data['completed']
            todo.is_completed = is_completed
            todo.save()
            message_status = 'complete' if is_completed else 'uncomplete'
            messages.success(request, f"TODO '{todo.title}' marked as {message_status}.")
        
        else:
            messages.warning(request, "Invalid action")

        return redirect('core:todo_list')

backend/core/templates/core/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'core/images/favicon.png' %}" type="image/x-icon">
    <title>TODO App - {% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'core/_message.html' %}
    {% block content %}{% endblock content %}
</body>
</html>

backend/core/templates/core/_message.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

backend/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'core/images/favicon.png' %}" type="image/x-icon">
    <title>TODO App - {% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'core/_message.html' %}
    {% block content %}{% endblock content %}
</body>
</html>

backend/core/templates/core/home.html
{% extends 'core/_base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Welcome to TODO App</h1>
{% endblock content %}

backend/core/templates/core/todo_confirm_delete.html
{% extends 'core/_base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
<a href="{% url 'core:todo_list' %}">See Todo List</a>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" Todo?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

backend/core/templates/core/todo_create.html
{% extends 'core/_base.html' %}

{% block title %}Create{% endblock title %}

{% block content %}
<a href="{% url 'core:todo_list' %}">See Todo List</a>
<h1>Create Your TODO</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="reset" value="Reset">
    <input type="submit" value="Save">
</form>
{% endblock content %}

backend/core/templates/core/todo_detail.html
{% extends 'core/_base.html' %}

{% block title %}Detail{% endblock title %}

{% block content %}
<a href="{% url 'core:todo_list' %}">See Todo List</a>
<h1>Title: {{ todo.title }}</h1>
<p>Description: {{ todo.description }}</p>
<p>Status: 
    {% if todo.is_completed %}
    ✅
    {% else %}
    🕓
    {% endif %}
</p>
<p>Due Date: 
    {% if todo.due_date %} 
        {{ todo.due_date|date:"DATETIME_FORMAT" }}
    {% else %}
        N/A
    {% endif %}
</p>
<p>Created At: {{ todo.created_at|date:"DATETIME_FORMAT" }}</p>
<p>Last Modified At: {{ todo.updated_at|date:"DATETIME_FORMAT" }}</p>
{% endblock content %}

backend/core/templates/core/todo_form.html
{% extends 'core/base.html' %}

{% block title %}Create{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="reset" value="Reset">
    <input type="submit" value="Save">
</form>
{% endblock content %}

backend/core/templates/core/todo_list.html
{% extends 'core/_base.html' %}

{% block title %}List{% endblock title %}

{% block content %}
<a href="{% url 'core:todo_create' %}">Create New Todo</a>
<h1>Your TODO's</h1>
<table border="2">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Due Date</th>
        <th>Created At</th>
        <th>Last Modified At</th>
        <th>View</th>
        <th>Update</th>
        <th>Delete</th>
        <th>Update Complete Status</th>
    </tr>
    {% for todo in todo_list %}
        <tr>
            <td>{{ todo.title }}</td>
            <td>{{ todo.description }}</td>
            <td>
                {% if todo.is_completed %}
                    ✅
                {% else %}
                    🕓
                {% endif %}
            </td>
            <td>
                {% if todo.due_date %} 
                    {{ todo.due_date|date:"DATETIME_FORMAT" }}
                {% else %}
                    N/A
                {% endif %}
            </td>
            <td>{{ todo.created_at|date:"DATETIME_FORMAT" }}</td>
            <td>{{ todo.updated_at|date:"DATETIME_FORMAT" }}</td>
            <td><a href="{% url 'core:todo_detail' todo.id %}">View Detail</a></td>
            <td><a href="{% url 'core:todo_update' todo.id %}">Update Detail</a></td>
            <td><a href="{% url 'core:todo_delete' todo.id %}">Delete</a></td>
            <td>
                <form action="{% url 'core:todo_update_completed' todo.id %}" method="post">
                    {% csrf_token %}
                    {% if todo.is_completed %}
                        <input type="checkbox" name="completed" id="id_completed" hidden>
                        <button>Mark Complete</button>
                    {% else %}
                        <input type="checkbox" name="completed" id="id_completed" checked hidden>
                        <button>Mark Uncomplete</button>
                    {% endif %}
                </form>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}

backend/core/templates/core/todo_update.html
{% extends 'core/_base.html' %}

{% block title %}Update{% endblock title %}

{% block content %}
<a href="{% url 'core:todo_list' %}">See Todo List</a>
<h1>Update Your TODO</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="reset" value="Clear Changes">
    <input type="submit" value="Save">
</form>
{% endblock content %}